config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories, only: [:index, :new, :create] do
    resources :operations, only: [:index]
  end

  resources :operations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :current_user

  has_and_belongs_to_many :operations
  has_one_attached :image

  validates :name, presence: true, length: { minimum: 3 }

  def current_user_operations
    operations.where(author: current_user)
  end

  def total_amount
    current_user_operations.sum(:amount)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :operations, inverse_of: :author, foreign_key: :author_id

  validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_signup_params, only: [:create], if: :devise_controller?

  protected

  def registration_controller?
    devise_controller? && resource_name == :user && action_name == 'create'
  end

  def configure_signup_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @categories.each { |category| category.current_user = current_user }
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def index
    @category = Category.includes(:operations).find(params[:category_id])
    @category.current_user = current_user
    @operations = @category.current_user_operations.order(created_at: :desc)
  end

  def new
    @operation = Operation.new
    @category = Category.find(params[:category_id])
  end

  def create
    @operation = Operation.new(operation_params)
    @operation.author = current_user

    if @operation.save
      redirect_to category_operations_path(@operation.categories.first)
    else
      render :new
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/categories/index.html.erb
<header class="d-flex align-items-center p-3 bg-primary text-white fs-4">
  <i id="open-drawer-icon" class="fa fa-bars"></i>
  <span class="w-100 text-center">Categories</span>
  <i class="fa fa-search"></i>
</header>

<% if @categories.empty? %>
  <div class="position-absolute top-50 w-100">
    <h2 class="text-center">Click on the button below to create a new category</h2>
  </div>
<% else %>
  <div class="list-group m-2 pb-5">
    <% @categories.each do |category| %>
      <%= link_to category_operations_path(category), class: "shadow rounded list-group-item card p-0 mb-2" do %>
        <h2 class="card-header"><%= category.name %></h2>
        <div class="card-body d-flex justify-content-between align-items-center pt-3">
          <% if category.image.attached? %>
            <%= image_tag category.image, class: "img-thumbnail w-25 p-0", style: "aspect-ratio: 1" %>
          <% else %>
            <%= image_tag "default-category.png", class: "img-thumbnail w-25 p-0", style: "aspect-ratio: 1" %>
          <% end %>
          <span style="font-size: xx-large">$<%= category.total_amount %></span>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<div class="fixed-bottom bg-success py-3 text-center">
  <%= link_to "Add a new category", new_category_path, class: "border px-5 py-2 text-decoration-none", style: "color: #fff" %>
</div>

<%= render 'partials/menu' %>

app/views/categories/new.html.erb
<header class="d-flex align-items-center p-3 fs-4 text-white bg-primary">
  <%= link_to categories_path do %>
    <i class="fa fa-arrow-left text-white"></i>
  <% end %>
  <span class="w-100 text-center">Add Category</span>
</header>

<%= form_for(@category, html: {class: "mt-3 h-100"}) do |f| %>
  <div class="card">
    <div class="form-floating ms-3">
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control border-start-0 border-top-0 border-end-0 border-bottom-0 shadow-none", placeholder: "John Doe" %>
      <%= f.label :name %>
    </div>

    <div class="form-floating ms-3">
      <%= f.file_field :image, class: "form-control border-start-0 border-end-0 shadow-none" %>
    </div>
  </div>

  <div class="fixed-bottom bg-success py-2 text-center">
    <%= f.submit "Save", class: "btn btn-success border px-5 text-white" %>
  </div>
<% end %>

app/views/home/index.html.erb
<p class="position-absolute top-50 w-100 text-center fw-italic fs-5">Budget App</p>

<div class="fixed-bottom px-3">
  <div class="bg-primary py-3 text-center shadow rounded mb-2">
    <%= link_to "LOG IN", new_user_session_path, class: "px-5 py-2 text-decoration-none", style: "color: #fff" %>
  </div>
  <div class="bg-white py-3 text-center shadow rounded">
    <%= link_to "SIGN UP", new_user_registration_path, class: "px-5 py-2 text-decoration-none", style: "color: #000" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
<head>
  <title>Budget App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />

  <style>
    .visible {
        display: flex!important;
    }
  </style>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="container-fluid p-0 h-100">
<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $('.multiple-select-field').select2({
        theme: "bootstrap-5",
        width: $( this ).data( 'width' ) ? $( this ).data( 'width' ) : $( this ).hasClass( 'w-100' ) ? '100%' : 'style',
        placeholder: $( this ).data( 'placeholder' ),
    });
</script>
</body>
</html>

app/views/operations/index.html.erb
<header class="d-flex align-items-center p-3 fs-4 text-white bg-primary">
  <%= link_to categories_path do %>
    <i class="fa fa-arrow-left text-white"></i>
  <% end %>
  <span class="w-100 text-center">Transactions</span>
  <i class="fa fa-search"></i>
</header>

<div class="card mb-3">
  <div class="card-body d-flex justify-content-between">
    <h2><%= @category.name %></h2>
    <h3>$<%= @category.total_amount %></h3>
  </div>
</div>

<% if @operations.empty? %>
  <div class="position-absolute top-50 w-100">
    <h2 class="text-center">Click on the button below to create a new transaction</h2>
  </div>
<% else %>
  <div class="list-group m-2 pb-5">
    <% @operations.each do |operation| %>
      <div class="shadow rounded list-group-item card p-0 mb-2">
        <div class="card-body d-flex justify-content-between align-items-center pt-3">
          <h2><%= operation.name %></h2>
          <h3>$<%= operation.amount %></h3>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="fixed-bottom bg-success py-3 text-center">
  <%= link_to "Add a new transaction", new_operation_path(category_id: @category.id), class: "border px-5 py-2 text-decoration-none", style: "color: #fff" %>
</div>

app/views/operations/new.html.erb
<header class="d-flex align-items-center p-3 fs-4 text-white bg-primary">
  <%= link_to category_operations_path(@category) do %>
    <i class="fa fa-arrow-left text-white"></i>
  <% end %>
  <span class="w-100 text-center">Add Transaction</span>
</header>

<%= form_for(@operation, html: { class: "mt-3 h-100" }) do |f| %>
  <div class="card">
    <div class="form-floating ms-3">
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control border-start-0 border-top-0 border-end-0 border-bottom-0 shadow-none", placeholder: "John Doe" %>
      <%= f.label :name %>
    </div>

    <div class="form-floating ms-3">
      <%= f.number_field :amount, autocomplete: "amount", class: "form-control border-start-0 border-end-0 border-bottom-0 shadow-none", placeholder: "$0.0" %>
      <%= f.label :amount %>
    </div>

    <div class="form-floating ms-3">
      <%= f.select :category_ids, Category.all.collect { |c| [c.name, c.id] }, { include_blank: true, include_hidden: false }, multiple: true, "data-placeholder": "Select categories", class: 'multiple-select-field border-start-0 border-end-0 border-bottom-0 shadow-none w-100' %>
    </div>
  </div>

  <div class="fixed-bottom bg-success py-2 text-center">
    <%= f.submit "Save", class: "btn btn-success border px-5", style: "color: #fff" %>
  </div>
<% end %>

app/views/partials/_menu.html.erb
<div id="drawer-menu" class="position-absolute fixed-bottom fixed-top" style="z-index: 1060; display: none">
  <div class="h-100 w-50 bg-primary">
    <div class="card bg-primary">
      <div class="card-header p-3 fs-4 text-white">
        <i id="close-drawer-icon" class="fa fa-arrow-left"></i>
        <span>Blog App</span>
      </div>
    </div>
    <div class="card-body list-group">
      <div class="d-flex align-items-center list-group-item bg-primary border-0 text-white">
        <i class="fa fa-user me-2"></i>
        <span style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis"><%= current_user.name %></span>
      </div>
      <div class="d-flex align-items-center list-group-item bg-primary border-0 text-white">
        <i class="fa fa-sign-out-alt me-2"></i>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-white text-decoration-none" %>
      </div>
    </div>
  </div>
  <div id="drawer-menu-outer" class="h-100 w-50 bg-dark" style="--bs-bg-opacity: .5"></div>
</div>
<script>
    document.querySelectorAll('#close-drawer-icon, #drawer-menu-outer').forEach(function (element) {
        element.addEventListener('click', function () {
            document.getElementById('drawer-menu').classList.remove('visible');
        });
    });

    document.getElementById('open-drawer-icon').addEventListener('click', function () {
        document.getElementById('drawer-menu').classList.add('visible');
    });
</script>